### ISSUE TITLE
Useless and a lot of log message

### ISSUE THREAD

**Issue by Gebardensprache** [LeoMehraban/flowerpower#1]
when generators work, the log will print the message of generator energy storage amount.
https://github.com/LeoMehraban/flowerpower/blob/edc8b1ae2d2f845b41e7d1569ca6ec1e7c90cd5a/src/main/java/com/leomeh/flowerpower/metatileentities/custom/ManaGeneratorTileEntity.java#L34
delete it plz

**Comment by LeoMehraban** [comment]
That was a debug line that I forgot to remove. I'll delete it immediately

**Comment by LeoMehraban** [comment]
Ok. that should be done. The update should be on curse forge shortly

**Comment by tong-ge** [comment]
hahaha, mod with built-in console spammer
